version: "3.9"

services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile
    image: demo-app:redis
    container_name: backend
    depends_on:
      mariadb:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      TZ: ${TZ:-UTC}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      SPRING_CONFIG_LOCATION: /config/
      SPRING_REDIS_HOST: ${SPRING_REDIS_HOST}
      SPRING_REDIS_PORT: ${SPRING_REDIS_PORT}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      SERVER_PORT: ${APP_PORT}
    ports:
      - "${APP_PORT:-8080}:8080"
    volumes:
      - ./docker/config:/config:ro
    networks: [ backend ]
    restart: unless-stopped

  mariadb:
    image: mariadb:10.11
    container_name: mariadb
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_PASS}
      MARIADB_DATABASE: ${DB_NAME}
    ports:
      - "3306:3306"
    volumes:
      - db_redis:/var/lib/mysql
      - ./docker/initdb:/docker-entrypoint-initdb.d:ro
    networks: [ backend ]
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u${DB_USER}", "-p${DB_PASS}" ]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 10s

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    depends_on:
      mariadb:
        condition: service_healthy
    environment:
      PMA_HOST: ${DB_HOST}
      PMA_PORT: ${DB_PORT}
      UPLOAD_LIMIT: 32M
    ports:
      - "8081:80"
    networks: [ backend ]
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks: [ backend ]
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

networks:
  backend:
    external: true

volumes:
  db_redis:
