version: "3.9"
services:
  app:
    image: demo-app:local
    container_name: backend_prod
    depends_on:
      mariaDB:
        condition: service_healthy
    environment:
      TZ: ${TZ:-UTC}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-prod}
      SPRING_CONFIG_LOCATION: /config/
      DB_HOST: mariaDB
      DB_PORT: 3306
      DB_NAME: ${DB_NAME:-authorization}
      DB_USER: ${DB_USER:-root}
      DB_PASS: ${DB_PASS:-root123}
      SERVER_PORT: 8080
    ports:
      - "${APP_PORT:-8080}:8080"
    volumes:
      - ./docker/config:/config:ro
    networks: [ backend ]
    restart: unless-stopped

  mariaDB:
    image: mariadb:10.11
    container_name: mariadb_prod
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: root123
      MARIADB_DATABASE: ${DB_NAME:-authorization}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/initdb:/docker-entrypoint-initdb.d:ro
    networks: [ backend ]
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot123" ]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 10s

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin_prod
    depends_on:
      mariaDB:
        condition: service_healthy
    environment:
      PMA_HOST: mariaDB
      PMA_PORT: 3306
      UPLOAD_LIMIT: 32M
    ports:
      - "8081:80"
    networks: [ backend ]
    restart: unless-stopped

networks:
  backend:
    external: true

volumes:
  db_data: